settings :
    - general :
        # application name default = foundation
        - name : "application.name"
          label : "setting.general.application.name"
          description : "setting.general.application.name.description"
          default : "Foundation"
          type : "string"
          input : "text"
          validation : "required|max:255"
        # application name bold length = 3
        - name : "application.name.bold"
          label : "setting.general.application.name.bold"
          description : "setting.general.application.name.bold.description"
          default : "3"
          type : "integer"
          input : "text"
          validation : "required|max:100"
        # application accronyme = fdt
        - name : "application.accronyme"
          label : "setting.general.application.accronyme"
          description : "setting.general.application.accronyme.description"
          default : "FDT"
          type : "string"
          input : "text"
          validation : "required|max:3"
        # application footer license to = company name
        - name : "application.footer.license.to"
          label : "setting.general.application.footer.license.to"
          description : "setting.general.application.footer.license.to.description"
          default : "Amazing Company"
          type : "string"
          input : "text"
          validation : "required|max:255"
        # application footer license link = no link
        - name : "application.footer.license.link"
          label : "setting.general.application.footer.license.link"
          description : "setting.general.application.footer.license.link.description"
          default : "#"
          type : "string"
          input : "text"
          validation : "required|max:255"
        # application footer info = some string display on footer right
        - name : "application.footer.info"
          label : "setting.general.application.footer.info"
          description : "setting.general.application.footer.info.description"
          default : "created by palagorn.p"
          type : "string"
          input : "text"
          validation : "required|max:255"
        # generic pagination limit = 15
        - name : "pagination.limit"
          label : "setting.general.pagination.limit"
          description : "setting.general.pagination.limit.description"
          default : "15"
          type : "integer"
          input : "text"
          validation : "required|max:1000"

    - user :
        # login can use username or email setting here.
        - name : "login.using"
          label : "setting.user.login.using"
          description : "setting.user.login.using.description"
          default : "email"
          type : "string"
          input : "select"
          validation : "required"
          choices : "email:Email,username:Username"
        # single signon login can config here
        - name : "login.strategic"
          label : "setting.user.login.strategic"
          description : "setting.user.login.strategic.description"
          default : "single"
          type : "string"
          input : "select"
          validation : "required"
          choices : "single:Single Signon,multiple:Multiple Signon"
        # redirect after login for default
        - name : "login.redirect"
          label : "setting.user.login.redirect"
          description : "setting.user.login.redirect.description"
          default : "/dashboard"
          type : "string"
          input : "text"
          validation : "required"

    - media :
        # Media Thumb Width.
        - name : "media.thumb.width"
          label : "setting.media.thumb.width"
          description : "setting.media.thumb.width.description"
          default : "200"
          type : "integer"
          input : "text"
          validation : "required|integer"
        # Media Thumb Height.
        - name : "media.thumb.height"
          label : "setting.media.thumb.height"
          description : "setting.media.thumb.height.description"
          default : "200"
          type : "integer"
          input : "text"
          validation : "required|integer"
        # Max Size in Megabytes
        - name : "media.max.size"
          label : "setting.media.max.size"
          description : "setting.media.max.size"
          default : "10"
          type : "integer"
          input : "text"
          validation : "required|integer"